name: Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"

      - name: Setup SSH to install dependencies
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: npm ci

      - name: Compile Contracts and Check Coverage
        run: npm run compile && npm run coverage

      - name: Publish to Codecov.io
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
