name: Subgraph

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - "*"

jobs:
  lint_subgraph:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"

      - name: Setup SSH to install dependencies
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: npm ci

      - name: Run Truffle Compile
        run: npm run compile-abi

      ### Subgraph Lint ###

      - name: Install Subgraph dependencies
        run: npm ci
        working-directory: subgraph

      - name: Generate subgraph files
        run: npm run codegen
        working-directory: subgraph

      - name: Build subgraph
        run: |
          ls -lotr
          npm run build
        working-directory: subgraph
